#- name: stop tomcat
#  service: name={{ tomcat_service_name }} state=stopped
#- name: start tomcat
#  service: name={{ tomcat_service_name }} state=started
- name: stop tomcat
  command: /etc/init.d/tomcat stop
- name: pause tomcat
  pause: seconds=10 prompt="Restarting"
- name: start tomcat
  command: /etc/init.d/tomcat start
